name: Test project

on: 
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '00 9 * * *' 

jobs:
  editmodeTests:
    name: Editmode Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: ./Library
          key: Library-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-

      - uses: game-ci/unity-setup@v2
        with:
          unityVersion: 6000.3.7f1
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - uses: game-ci/unity-test-runner@v4
        id: editmodeTests
        with:
          unityVersion: 6000.3.7f1
          projectPath: ./
          testMode: editmode
          artifactsPath: editmode-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Editmode Test Results

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Editmode Test Results
          path: ${{ steps.editmodeTests.outputs.artifactsPath }}

  playmodeTests:
    name: Playmode Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: ./Library
          key: Library-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-

      - uses: game-ci/unity-setup@v2
        with:
          unityVersion: 6000.3.7f1
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - uses: game-ci/unity-test-runner@v4
        id: playmodeTests
        with:
          unityVersion: 6000.3.7f1
          projectPath: ./
          testMode: playmode
          artifactsPath: playmode-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Playmode Test Results

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Playmode Test Results
          path: ${{ steps.playmodeTests.outputs.artifactsPath }}
